### ISSUE TITLE
Does Relay work with a LiteSpeed server

### ISSUE THREAD

**Issue by nickchomey** [cachewerk/relay#10]
You mention PHP-FPM in your documentation. Does this mean that Relay cannot be used with a LiteSpeed/OpenLiteSpeed server, which uses its own LSAPI extensions?

For more context, you say the requirements are the following php extensions: json, igbinary, and msgpack. I have the lsphp versions of those. 

Thanks!

**Comment by tillkruss** [comment]
Yes, Relay works with Litespeed. I'll update the docs.

**Comment by tillkruss** [comment]
Related https://github.com/cachewerk/linux-repos/issues/6

**Comment by tillkruss** [comment]
I've added a Docker example for OpenLiteSpeed: https://github.com/cachewerk/relay/commit/38545dc9f2aa0732708ad3ab1f4dafed63b1e526
