### ISSUE TITLE
Can't install on Debian bookworm (apt) and PHP 8.1-8.2

### ISSUE THREAD

**Issue by conf** [cachewerk/relay#128]
`relay.so` seems to be compiled against wrong library versions, the ones I can't install from packages.

## Description
Debian bookworm has libssl3 (3.0.11-1~deb12u2) and `relay.so` is built against libssl.so.1.1 and libcrypto.so.1.1.
## Expected Behavior
`php --ri relay` reports proper configuration and no errors shown.
## Actual Behavior
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'relay.so' (tried: /usr/lib/php/20210902/relay.so (libssl.so.1.1: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/relay.so.so (/usr/lib/php/20210902/relay.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Extension 'relay' not present.
	linux-vdso.so.1 (0x0000ffffb12a1000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffffb1120000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffb0f70000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffffb1264000)
	libzstd.so.1 => /lib/aarch64-linux-gnu/libzstd.so.1 (0x0000ffffb0eb0000)
	liblz4.so.1 => /lib/aarch64-linux-gnu/liblz4.so.1 (0x0000ffffb0e60000)
	libanl.so.1 => /lib/aarch64-linux-gnu/libanl.so.1 (0x0000ffffb0e30000)
```

## Possible Fix

I tried custom build from https://builds.r2.relay.so/v0.7.0/relay-v0.7.0-php8.2-debian-aarch64+libssl3.tar.gz and file `relay-pkg.so` seems to work, but it was quite a puzzle to find that specific link there and try that file. 

Btw, `relay.so` is not working, it also has some libraries missing:
```
 ldd relay.so
	linux-vdso.so.1 (0x0000ffff8dd2e000)
	libhiredis_ssl.so.1.1.0 => not found
	libhiredis.so.1.1.0 => not found
	libssl.so.3 => /lib/aarch64-linux-gnu/libssl.so.3 (0x0000ffff8db40000)
	libcrypto.so.3 => /lib/aarch64-linux-gnu/libcrypto.so.3 (0x0000ffff8d6e0000)
	libck.so.0 => not found
	libzstd.so.1 => /lib/aarch64-linux-gnu/libzstd.so.1 (0x0000ffff8d620000)
	liblz4.so.1 => /lib/aarch64-linux-gnu/liblz4.so.1 (0x0000ffff8d5d0000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff8d420000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffff8dcf1000)
```
Bookworm is missing libhiredis 1.1.0, it only has `libhiredis0.14`.

## Steps to Reproduce
I used the following Dockerfile (I'm on a mac, so arm64 arch, but that probably doesn't matter). This is almost exact copy of [one of your examples](https://github.com/cachewerk/relay/blob/main/docker/debian/debian11-apt.Dockerfile) with some minor tweaks, like Debian version, php8.2 version and custom CMD command to simplify the test case.
```
FROM debian:12

RUN apt-get update

RUN apt-get install -y \
  wget \
  gnupg \
  lsb-release

RUN wget -q "https://packages.sury.org/php/apt.gpg" -O /usr/share/keyrings/ondrej.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/ondrej.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/ondrej.list > /dev/null
RUN apt-get update

RUN apt-get install -y \
  php8.2-fpm

# Add Relay repository
RUN wget -q "https://repos.r2.relay.so/key.gpg" -O- | gpg --dearmor -o /usr/share/keyrings/cachewerk.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/cachewerk.gpg] https://repos.r2.relay.so/deb $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/cachewerk.list > /dev/null
RUN apt-get update

# Install Relay
RUN apt-get install -y \
  php8.2-relay

CMD php --ri relay; ldd /usr/lib/php/2*/relay.so
```
Copy the above file into some folder like `/tmp/relay/`, build the image and run a container from it:
```bash
mkdir /tmp/relay
cd /tmp/relay
vim Dockerfile # paste the contents of Dockerfile to the file and save
docker build . --no-cache -t relay-debian-12-8.2 
docker run -it --rm relay-debian-12-8.2
```

## Relay diagnostics

```
...
```

## Environment

* OS and version: macOS Sonoma 14.2.1
* PHP version: PHP 8.2
* Redis version: not installed

**Comment by michael-grunder** [comment]
Thanks for the report.  Looks like an OpenSSL version issue.  We have builds targeting openssl 3 as well.

I've got an aarch64 (M1) mac so I can get this working locally and then post my dockerfile.

**Comment by tillkruss** [comment]
@conf Thanks, the `bookworm` builds were using the wrong `libssl` version because of a missing case: https://github.com/cachewerk/linux-repos/commit/2fdd77946c3801d25853f10b7bee7813db33ba0f

I'll trigger a new build, the repo will update shortly.

**Comment by conf** [comment]
Thank you for quick response, but my `apt-get install` command still gives me wrong `relay.so` file (see my reproduction `Dockerfile` above). Was there a repo update recently?

**Comment by tillkruss** [comment]
@conf Sorry, I should have posted an update. We just finished the sync for v0.7.0 and I flushed the edge cache. The install should work as of a few minutes ago.

**Comment by conf** [comment]
Hate to be a PITA but it's still not working on my side. Could you please check again?

**Comment by yatsukhnenko** [comment]
@conf as a workaround you can try to install previous version
```bash
apt install php8.1-relay=0.6.8
```

**Comment by yatsukhnenko** [comment]
@tillkruss it looks like there are no builds for 0.7.0 and PHP > 8.0

**Comment by tillkruss** [comment]
We've had this once before where we tried to re-build a release and it failed badly. We ended up tagging a new release instead.

I think we need a [few extra Docker containers](https://github.com/cachewerk/relay/tree/main/docker) to proof the repos are working. I'll add some now.

> @tillkruss it looks like there are no builds for 0.7.0 and PHP > 8.0

Can you show me what you ran to determine this?

**Comment by tillkruss** [comment]
Okay, added in 9007bc9255d551908b1375fe34885e3074d2fd9d. [CI passes](https://github.com/cachewerk/relay/actions/runs/8085434699/job/22092939994).

This builds for me:

```bash
docker build --pull --tag relay-debian12 --file debian12-apt.Dockerfile .
docker run -it relay-debian12 bash
php --ri relay
```

@conf: I'm guessing your local `apt` cache has old data? A `sudo apt-get clean` might resolve it, or maybe a similar command.

If that doesn't work, can you post the Dockerfile you're using or details about the setup?

**Comment by szepeviktor** [comment]
You can always look around in the Packages file.
https://repos.r2.relay.so/deb/dists/bookworm/main/binary-amd64/Packages

**Comment by conf** [comment]
Hello @tillkruss, thank you for the update and sorry for a delayed response from my part.
Indeed, my build is working now with PHP 8.3 and Debian 12, but not working on lower PHP versions like 8.2 and 8.1.
Could you please fix the build at least for Debian 12 and PHP 8.2 (since that's what we use in production at the moment)?
> @conf: I'm guessing your local apt cache has old data? A sudo apt-get clean might resolve it, or maybe a similar command.

No, my apt cache is not stale, checked several times. I use the exact script provided in `Steps to Reproduce` in this issue, I've also added `--no-cache` option to `docker build` command to make it repeatable.

I can still use the provided workaround with downloading `relay.so` by a direct link, but it would be also nice to have a streamlined installation just with `apt-get` tools.
Thank you again for your hard work.

**Comment by tillkruss** [comment]
> Hello @tillkruss, thank you for the update and sorry for a delayed response from my part. Indeed, my build is working now with PHP 8.3 and Debian 12, but not working on lower PHP versions like 8.2 and 8.1. Could you please fix the build at least for Debian 12 and PHP 8.2 (since that's what we use in production at the moment)?

You're right, I can reproduce this:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'relay.so' (tried: /usr/lib/php/20220829/relay.so (libssl.so.1.1: cannot open shared object file: No such file or directory), /usr/lib/php/20220829/relay.so.so (/usr/lib/php/20220829/relay.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Extension 'relay' not present.
```

> I can still use the provided workaround with downloading `relay.so` by a direct link, but it would be also nice to have a streamlined installation just with `apt-get` tools. Thank you again for your hard work.

Totally.

**Comment by tillkruss** [comment]
@conf: I think we worked it out. It should install now. I believe this was the issue: https://github.com/cachewerk/linux-repos/commit/36551f97273577632f06bb40b29a55d7398980db

**Comment by conf** [comment]
It works now. Thanks again!
