### ISSUE TITLE
WordPress Object Cache Failover handling in Sentinel Error state

### ISSUE THREAD

**Issue by tillkruss** [cachewerk/relay#139]
We had some repeated major issues with our Redis and OCP Setup within the last couple of days.
To recap: We run Redis + Sentinel on 2 DB Cluster Server Nodes + x Web-Server Nodes (minimum 5 in total; 1 master on the DB Nodes + 1 DB slave + n Web slaves). Within OCP / WordPress  / wp-config.php there are three Redis Sentinel nodes configured as you suggested:
- 127.0.0.1
- DB Cluster 1
- DB Cluster 2

The scenario that happens was always the same: For different reasons the redis Sentinel Setup turned partly unhealthy. For example one web-server run out of memory and killed the redis process - which was just a slave within the sentinel setup... On another event the current master died due to RAM failures. The first event should not have had any impact on the setup. But it did the same as the second event.

The following issues were rather unexpected and very unpleasant but always the same:
ALL Web-Servers / WordPress / OCP went into an error state where they all reported that "No valid sentinels could be found". Which is strange as with the configuration of three sentinels  from which at least two were very much alive we did not expect this to be able to happen on all servers and actually "spread". We would have understood this during the failover of the master. But it was highly unexpected when just one slave node went out of the setup. 
This might be Redis related in general - or not - and maybe you have a better understanding of Redis than we have. So I hope that you might have an idea what's wrong about our setup which actually should be high available?!

The second issue is much more OCP / WordPress: When the redis sentinel connection is "lost" we encounter some Plugins which go haywire. Instead of falling back to the Database connection it seems like their calls to WPs get_option return a value they don't expect and assume that the option they are expecting is missing. This then leads to the "setup" code being triggered and a broken / empty / new config is persisted into the database although the correct values were there all the time. Even fixing the Redis connection leaves a broken state as the actual working options are gone for good and overwritten with empty ones.
We clearly identified this in "WP Mail SMTP" on sites with a lot of mail traffic. But there might be other plugins as well. We were able to contain the issue or disable OCP in these events quite quickly so only those plugins which were triggered frequently and were broken after redis worked again were the obvious findings.

This might be something between the return value handling of OCP or maybe even some architectural issues in WordPress. Still this caused us repeatedly high costs due to manual restore processes of these broken options on many sites.

My expectations would be that in the case of a broken Redis connection the system falls back to the Database with no Object Caching. But this does not seem to be the case. At least not reliably. Do we have wrong expectations here? Or are we missing something obvious? Do you have any suggestions how to achieve a reliable failover to the Database when redis does not respond?

```php
define('WP_REDIS_CONFIG', [
    'sentinels' => [
        'tcp://127.0.0.1:26379',
        'tcp://10.0.0.23:26379',
        'tcp://10.0.0.24:26379',
    ],
    'service' => 'mymaster',
    'password' => '<its-the-real-password>',
    'persistent' => true,
    'timeout' => 0.5,
    'read_timeout' => 0.5,
    'retry_interval' => 50,
]);
```

**Comment by yatsukhnenko** [comment]
Any sentinel settings were changed or default values are used? I'm asking because by default there are relatively high timeout values to mark master host down and re-start failover process

**Comment by JanThiel** [comment]
@yatsukhnenko 

```
protected-mode no
supervised systemd
port 26379

requirepass "<PASS>"
sentinel monitor mymaster 10.0.0.1 6379 2
sentinel auth-pass mymaster <PASS>
sentinel down-after-milliseconds mymaster 5000

sentinel failover-timeout mymaster 10000
sentinel deny-scripts-reconfig yes
...
```

**Comment by yatsukhnenko** [comment]
@JanThiel thanks. On my local setup I found that in some situations OCP may not use connection to new master when it failed to connect to its slaves. Are there any records in the logs which may help me to identify the problem?

**Comment by JanThiel** [comment]
@yatsukhnenko No idea if it helps but here is a small portion of the logs:

```
[error] 3200075#3200075: *1281266 FastCGI sent in stderr: "
PHP message: objectcache.error: Failed to execute `GET` command
PHP message: objectcacdataset in memory
PHP message: objectcache.error: Failed to execute `GET` command
PHP message: objectcache.error: Failed to execute `GET` command
PHP message: objectcache.error: LOADING Redis is loading the de.error: Unable to connect to any valid sentinels 
PHP message: 
PHP Warning:  Undefined property: RedisCachePro\Connections\PhpRedisSentinelsConnection::$primary in  /web/wp-ce: 
PHP Warning:  Undefined property: RedisCachePro\Connections\PhpRedisSentinelsConnection::$sentinel in  /web/wp-content/plugins/object-cache-pro/src/Connections/Concerns/Sels 
PHP Warning:  Undefined property: RedisCachePro\Connections\PhpRedisSentinelsConnection::$pool in  /web/wp-content/plugins/object-cache-pro/src/Connections/Coarray) must be of type array, null given
PHP message: PHP Warning:  Undefined property: RedisCachePro\Connections\PhpRedisSentinelsConnection::$primary in  /web/wp-content/pluning:  Undefined property: RedisCachePro\Connections\PhpRedisSentinelsConnection::$sentinel in  /web/wp-content/plugins/object-cache-pro/src/Connections/Concerns/SentinelsCon
[error] 3200077#3200077: *1281943 FastCGI sent in stderr: "ssage: objectcache.error: array_rand(): Argument #1 ($array) must be of type array, nnection::$primary in  /web/wp-content/plugins/object-cache-pro/src/Connections/Concerns/SentinelsConnection.php on line 103
PHP message: PHP Warning:  Undefined property: Redip-content/plugins/object-cache-pro/src/Connections/Concerns/SentinelsConnection.php on line 52
PHP message: objectcache.error: Unable to connect to any valid sentinels 
PHP message: PHP Warning:  Undefined p520/web/wp-content/plugins/object-cache-pro/src/Connections/Concerns/SentinelsConnection.php on line 102
PHP message: objectcache.error: array_rand(): Argument #1 ($array) must be of type array, null givenPprimary in  /web/wp-content/plugins/object-cache-pro/src/Connections/Concerns/SentinelsConnection.php on line 103
PHP message: PHP Warning:  Undefined property: RedisCachePro\plugins/object-cache-pro/src/Connections/Concerns/SentinelsConnection.php on line 52
PHP message: objectcache.error: Unable to connect to any valid sentinels PHP message: 
PHP Warning:  Undefined property: R-content/plugins/object-cache-pro/src/Connections/Concerns/SentinelsConnection.php on line 102
PHP message: objectcache.error: array_rand(): Argument #1 ($array) must be of type array, null given
```

**Comment by JanThiel** [comment]
@yatsukhnenko Were you able to close in on a solution already?
Any kind of an ETA would help us assess whether we need to switch off OCP for the time beeing or risk the current "state" for some more time as high availability with Sentinels obviously is broken. Thanks for confirming this!

**Comment by yatsukhnenko** [comment]
Hi @JanThiel 
I was able to find and fix this issue. Currently patch is under testing and code review.

**Comment by tillkruss** [comment]
@JanThiel: We're pushing a release by Monday latest with this fix.

**Comment by JanThiel** [comment]
Hey @tillkruss I still can't find a new release with the fix. Did I miss something?

**Comment by tillkruss** [comment]
@JanThiel Sorry, today it's coming.

**Comment by JanThiel** [comment]
@tillkruss I still do not see any update for Object Cache Pro?!
