### ISSUE TITLE
Fails to download msgpack

### ISSUE THREAD

**Issue by SamTyurenkov** [cachewerk/relay#142]
When running this as suggested on https://relay.so/docs/1.x/installation
![image](https://github.com/cachewerk/relay/assets/19373777/77452408-2664-4110-b3a1-78fb083c7d69)
I get an error, which fails to get some of the dependencies

## Description
```
 => ERROR [stage-0  8/15] RUN install-php-extensions relay                                                                                                                                                                                 58.9s
------
 > [stage-0  8/15] RUN install-php-extensions relay:
0.300 install-php-extensions v.2.2.17
1.321 Updating channel "pecl.php.net"
29.54 Channel "pecl.php.net" is not responding over http://, failed with message: File http://pecl.php.net:80/channel.xml not valid (redirected but no location)
29.54 Trying channel "pecl.php.net" over https:// instead
30.07 Channel "pecl.php.net" is up to date
30.32 Hit:1 http://deb.debian.org/debian bookworm InRelease
30.37 Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
30.44 Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
30.48 Reading package lists...
30.81 ### INSTALLING REMOTE MODULE msgpack ###
58.82 Package "msgpack" does not have REST info xml available
58.82 install failed
```

## Expected Behavior
It should install relay

## Actual Behavior
relay is not installed, pipeline fails

## Possible Fix
1) replace/remove msgpack from dependencies? 
2) contact msgpack as for a fix?
3) try different installer method, e.g. `RUN docker-php-ext-install
`
## Steps to Reproduce
1) just run a recommended installation for Docker

## Environment

* OS and version: official php8.1-fpm docker image (Debian based)

**Comment by SamTyurenkov** [comment]
**Update:** it seems to fail only from Russian IP. I was able to download it with VPN afterwards. 
Still seems like a reason to do something about it.

**Comment by michael-grunder** [comment]
Maybe pecl is just down?  I know the site sometimes breaks.

https://github.com/msgpack/msgpack-php/issues/140

**Comment by SamTyurenkov** [comment]
> Maybe pecl is just down? I know the site sometimes breaks.
> 
> [msgpack/msgpack-php#140](https://github.com/msgpack/msgpack-php/issues/140)

Nope, it somehow blocked inside a bundle. I was able to download it directly without VPN:
simply with `pecl install msgpack`

However at the same time, trying to get it through install-php-extensions failed.

**Comment by michael-grunder** [comment]
> Update: it seems to fail only from Russian IP. I was able to download it with VPN afterwards.
Still seems like a reason to do something about it.

I'm not sure how we could fix that.  I suppose we could use something other than `install-php-extensions`

**Comment by jdreesen** [comment]
Seems to be a problem in https://github.com/mlocati/docker-php-extension-installer. 
Maybe @mlocati can help?

**Comment by SamTyurenkov** [comment]
> > Update: it seems to fail only from Russian IP. I was able to download it with VPN afterwards.
> > Still seems like a reason to do something about it.
> 
> I'm not sure how we could fix that. I suppose we could use something other than `install-php-extensions`

there is native support of  `RUN docker-php-ext-install ` in official php images, maybe you could use that.

**Comment by mlocati** [comment]
> there is native support of `RUN docker-php-ext-install ` in official php images, maybe you could use that.

`docker-php-ext-install` is only able to install the PHP extensions that comes [bundled with PHP](https://github.com/php/php-src/tree/master/ext).

In order to install other extensions (for example from [PECL](https://pecl.php.net/)), you have to use `pecl`.

In both cases, you have to manually install the APT (for Debian)/APK (for Alpine) system packages that are required by every PHP extension you are going to install.

My `install-php-extensions` is *just* a wrapper around `docker-php-ext-install` and `pecl`, and it installs the required system packages.

So, I don't think the problem is related to `install-php-extensions`.

**Comment by yatsukhnenko** [comment]
@tillkruss @michael-grunder russia is a terrorist state and we should also consider blocking access to relay.so from their IPs
