### ISSUE TITLE
Valkey compatibility

### ISSUE THREAD

**Issue by szepeviktor** [cachewerk/relay#149]
## Description

Is Relay [Valkey](https://hub.docker.com/r/valkey/valkey/) compatible?
I mean tested.

## Expected Behavior

Yes!

## Actual Behavior

Donno.
It is getting popular https://upcloud.com/valkey

**Comment by michael-grunder** [comment]
I run Valkey when developing Relay and have not encountered any issues.

We can certainly add it to CI though.
