### ISSUE TITLE
PHP startup warning when installing via Homebrew

### ISSUE THREAD

**Issue by johnbillion** [cachewerk/relay#25]
After [installing via Homebrew](https://relay.so/docs/1.x/installation#content-macos) I get a PHP startup warning:

```
Warning: PHP Startup: Relay is using the default binary ID of '31415926-5358-9793-2384-626433832795' in Unknown on line 0
```

This warning prevents Valet from being able to restart PHP-FPM.

**Comment by michael-grunder** [comment]
Hi, thanks for the report,

I wasn't able to replicate this.  Is there anything specific about how you're `brew install`ing the package?

Also, are you installing stable or `HEAD`?

**Comment by johnbillion** [comment]
Thanks, AFAIK I'm using stable rather than head. I'm running PHP 8.0.

```
pecl install igbinary
pecl install msgpack
brew install relay@8.0
```

**Comment by tillkruss** [comment]
@johnbillion: I think v0.4.5 is completely bricked on macOS. The compiler did "code optimizations" and there is no way to fix the UUID issue for that release. We'll tag v0.4.6 shortly which will resolve this.

**Comment by tillkruss** [comment]
@johnbillion: Try #19.
