### ISSUE TITLE
Checking Reflections in Relay

### ISSUE THREAD

**Issue by szepeviktor** [cachewerk/relay#43]
- loop through each downloadable relay.so version
- find out/hardcode what PHP version/s are supported, loop though them
- find all methods in each built-in Relay class and check PHP compatibility

How to check PHP compatibility?

PHPStan says

> AST failed to parse in located source (line 245): Syntax error, unexpected '|'

Ask the author!

**Comment by tillkruss** [comment]
_Union types_ were added in 8.2 I believe.

**Comment by szepeviktor** [comment]
Currently I cannot find in PHPStan source code/deps where the above error happens.
I'd like to do the very same thing.

**Comment by szepeviktor** [comment]
Till! This work is very hard. I need to eat 🥘 
https://github.com/ondrejmirtes/BetterReflection/blob/6.4.x/src/SourceLocator/Type/PhpInternalSourceLocator.php#L16
I'll hire a developer ... 🙃

**Comment by szepeviktor** [comment]
Something is cooking ...

**Comment by tillkruss** [comment]
I don't think we need this anymore. Since https://github.com/JetBrains/phpstorm-stubs/tree/master/relay was merged.
