### ISSUE TITLE
PHP Startup: Relay is using the default binary ID in Unknown on line 0

### ISSUE THREAD

**Issue by ixqbar** [cachewerk/relay#44]
PHP Warning:  PHP Startup: Relay is using the default binary ID in Unknown on line 0
Warning: PHP Startup: Relay is using the default binary ID in Unknown on line 0

use relay-v0.5.1-php8.2-darwin-x86-64/relay-pkg.so
php 8.2.1

**Comment by tillkruss** [comment]
You need to inject an UUID, follow the installation instructions:
https://relay.so/docs/1.x/installation

**Comment by ixqbar** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/960982/215369892-992fb0e7-dd40-4a74-8a28-cfab08302c55.png">
<img width="676" alt="image" src="https://user-images.githubusercontent.com/960982/215369958-14f87759-e532-424b-9f7f-958e63e3a22c.png">


```
<?php

//phpinfo();
//exit();

$relay = new Relay;
echo $relay->get('i-do-not-exist');
```
