### ISSUE TITLE
Missing `subscribe()` method

### ISSUE THREAD

**Issue by devicenull** [cachewerk/relay#46]
I noticed that Relay doesn't appear to support the ::subscribe function that phpredis does - https://github.com/phpredis/phpredis#subscribe

It would be nice to have that either implemented or documented as being different

**Comment by tillkruss** [comment]
Yes, the pub/sub methods are still missing. That and Redis Cluster will come with v1.

**Comment by devicenull** [comment]
Well, ::publish is there, but it doesn't appear to work properly (publishing from relay & subscribing from phpredis just results in messages going into the void)

**Comment by tillkruss** [comment]
How are you using `subscribe()` currently with PhpRedis?

**Comment by devicenull** [comment]
We use the publish() method from php-fpm to communicate with a long-running script that's listening via subscribe().  This let's us do a little bit of background processing without blocking the main request flow.

**Comment by tillkruss** [comment]
Thanks, @devicenull. I think `publish()` is a no-op, but we'll get this implemented in the next release. I'll ping you once it's done.

**Comment by devicenull** [comment]
Thanks! No big rush from us, we just made it continue to use phpredis.  It's not a bottleneck at all for this use case

**Comment by tillkruss** [comment]
Added to roadmap for Q1: https://github.com/orgs/cachewerk/projects/3/views/1

Closing in favor of #49.
