### ISSUE TITLE
Build for php 8.3 / master

### ISSUE THREAD

**Issue by simpletoimplement** [cachewerk/relay#50]
Hey. I'm currently using php built from php-src master branch e.g. 8.3. Any way to get a build for this version? can't use php 8.2 build as module versions differ

**Comment by tillkruss** [comment]
Yes, we should be able to publish nightly builds for 8.3. Which platform are you working on? https://relay.so/builds

**Comment by simpletoimplement** [comment]
docker, alpine linux based

**Comment by tillkruss** [comment]
We typically start shipping builds with the Alpha 1. I'll look into this if we can ship them earlier.

**Comment by k0d3r1s** [comment]
hey. any eta on this? i would be interested in relay in alpine php 8.3 too

**Comment by tillkruss** [comment]
We're working on builds for PHP `master`. Got most of it building as of yesterday.

**Comment by tillkruss** [comment]
The first 8.3 builds are live.

**These are obviously considered unstable and may break at any point, just like PHP master. **

The good news is we now have `php-src:master` build pipelines, so 8.4, etc. will be much faster to ship.

**Comment by k0d3r1s** [comment]
awesome, thank you :)  
will let you know if it works when I build image with relay
