### ISSUE TITLE
Improve docs for `relay.max_endpoint_dbs`

### ISSUE THREAD

**Issue by devicenull** [cachewerk/relay#51]
> The maximum number of in-memory databases Relay will create per endpoint.

This documentation doesn't really give me any information about what this setting is, or if I need to be changing it.
Questions I have:
* Does this limit concurrency for a particular redis endpoint?
* How does this relate to relay.databases?
* Would I see better cache hit ratios by lowering this to like 1?

**Comment by tillkruss** [comment]
In progress.
