### ISSUE TITLE
Document minimum for `relay.maxmemory`

### ISSUE THREAD

**Issue by devicenull** [cachewerk/relay#52]
It looks like `relay.maxmemory` can't be set any lower then 16M - is that correct?

**Comment by michael-grunder** [comment]
Yes, right now the minimum non-zero value for `relay.maxmemory` is `1024 * 1024 * 16`.  Do you want to set it to a lower value?

**Comment by devicenull** [comment]
It's fine like that - I was lowering it to do some testing about cache evictions.  I mainly just wanted the docs updated

**Comment by tillkruss** [comment]
@devicenull: Yep, I've been putting a lot of effort into the docs over the last weeks. I'll update the `ini` comment.
