### ISSUE TITLE
Timeout / endless response

### ISSUE THREAD

**Issue by k0d3r1s** [cachewerk/relay#53]
Hello again.  
I have successfully built php 8.3 with relay (as discussed in #50) but there seems to be a problem.  
I have symfony project with https://github.com/snc/SncRedisBundle and as suggested in documentation, simply changing config from phpredis to relay should be sufficient enough to get everything working. But unfortunetely this does not work as it just results in endless response => timeout.  
Test from your documentation (https://relay.so/docs/1.x/installation#http-test) results in same timeout.  
this is `php -ri relay` response:  
```
relay

Relay Support => enabled
Relay Version => 0.6.2-dev
Available serializers => php, json, igbinary, msgpack
Available compression => lzf, zstd, lz4
Git SHA => 09915f3161b3ace120cf175708446bda0871bc0a
relay.enabled => true
relay.key =>  
relay.maxmemory => 33554432
relay.maxmemory_pct => 75
relay.maxmemory_limit => 33554432
relay.eviction_policy => noeviction
relay.eviction_sample_keys => 128
relay.initial_readers => 128
relay.invalidation_poll_usec => 5
relay.pconnect_default => 1
relay.max_endpoint_dbs => 32
Cache available => 33500240
Binary UUID => 38f15393-adc3-4661-84d6-683cf9d8128a
License state => unknown
License memory cap => 0
License request id =>  
relay.loglevel => none
relay.logfile => /var/log/relay.log
Allocator => relay
```
This is what is written in /var/log/relay.log:  
```
[1678479521.631641 DBG 6751] shmalloc.c:202 Allocated 33554432 byte pool (head: 7f28853bf000, curr: 7f28853c0020, alignment: 16)
[1678479521.631754 DBG 6751] cache.c:43 EPOCH[malloc]: 7f28853c6ea0 (5303 bytes)
[1678479521.631794 NOT 6751] relay.c:2212 STARTUP - Relay has started...
[1678479521.673917 DBG 6752] relay.c:2863 RINIT - Requests (1 total, 1 active, 1 max)
[1678479521.673940 DBG 6752] relay.c:2830 HTTP_HOST - Failed to find HTTP_HOST or it's not a string.
[1678479521.673945 DBG 6752] relay.c:2806 PLINK - Uninstalling handlers for 0 links
[1678479521.674294 NOT 6752] relay.c:3371 CRON TASKS - GC(keys): 1; GC(msg): 0, EVICTED: 0 keys
[1678479521.674304 NOT 6752] relay.c:3378 CRON  PROC - hits/miss: 0/0 (0.00%), oom: 0, errors: 0
[1678479521.674310 NOT 6752] relay.c:3329 CRON STATS - Memory 54144/33554432 bytes (0.16%)
[1678479521.674319 DBG 6752] relay.c:2737 PLINK - installing handlers for 0 links
[1678479521.674329 DBG 6752] relay.c:2956 RSHUTDOWN - Finished request
[1678479521.689842 DBG 6751] relay.c:2863 RINIT - Requests (2 total, 1 active, 1 max)
[1678479521.689864 DBG 6751] relay.c:2830 HTTP_HOST - Failed to find HTTP_HOST or it's not a string.
[1678479521.689869 DBG 6751] relay.c:2806 PLINK - Uninstalling handlers for 0 links
[1678479521.689964 DBG 6751] relay.c:2737 PLINK - installing handlers for 0 links
[1678479521.689975 DBG 6751] relay.c:2956 RSHUTDOWN - Finished request
[1678479521.700485 NOT 6751] relay.c:2235 Relay is shutting down, bye bye
```
If you want to check what is wrong on my build, here are:  
dockerfiles: https://github.com/k0d3r1s-library/docker-php-fpm  
image: https://hub.docker.com/layers/k0d3r1s/php-fpm/8.3.0-dev-testing/images/sha256-327757cf2eadca641a17b221e684142dcec24b54e0dbcec20088fff55fe64525

Edit: I am connecting to redis in different container, not on localhost

**Comment by tillkruss** [comment]
@k0d3r1s This is excellent, might be a 8.3 related issue with FPM. @michael-grunder can take a look at this next week.

**Comment by michael-grunder** [comment]
I'll take a look this weekend.

**Comment by simpletoimplement** [comment]
unfortunately my build has this same exact problem :( as far as i look at this issue, only difference is uuid, everything else is the same

**Comment by michael-grunder** [comment]
I found the issue.

The problem is a conflict between Relay's statically compiled version of `hiredis` (v1.0.1-dev), and `phpiredis`'s dynamically linked `hiredis` (in this case v1.1.0).

If you disable `phpiredis` on the container, `Relay` starts working.

We are statically linking to hiredis because at the time we started packaging Relay, we needed a bugfix that had yet to be published in an official hiredis release.  I have since done two hiredis releases so I'll add a build that links to hiredis dynamically.

This should solve the problem and get everything working again.

**Comment by tillkruss** [comment]
@michael-grunder can he not use the `relay.so` from our builds, I thought only the `relay-pkg.so` has hiredis baked in?

**Comment by michael-grunder** [comment]
@tillkruss Not really, or at least not in a way that's likely stable/safe.

The issue here is that there are two PHP extensions both using `hiredis`.  In this particular case, `phpiredis` was built against hiredis v1.1.0, and `relay` was statically built with a pre-release version ([5850a8ec](https://github.com/redis/hiredis/tree/5850a8ecd2fb4ab39d80773e3017f02aff097ec4)), which is causing the issue.

Not loading `phpiredis` solves the problem, but if we want to run both of them they'll both need to be pointing at the same version of hiredis.  For _this_ container, that's easy.  They can both point to hiredis v1.1.0.

There are more generic solutions such as Relay renaming the hiredis symbols we include statically, but I think updating Relay to use the latest stable hiredis is something we should do anyway.  We're only linking to that commit because it includes a bugfix we did that hadn't yet been in any actual release.

**Comment by k0d3r1s** [comment]
@michael-grunder Hey. I built image with relay.so from zip you added in comment above.  
Looks like it is working now, awesome.  
Only problem I have now is that `php -ri relay` now responds with this:  
```shell
$ php -ri relay
PHP Parse error:  syntax error, unexpected end of file in Command line code on line 1

Parse error: syntax error, unexpected end of file in Command line code on line 1
```
Actually, now every script using `php -r` responds with this. Removing relay from build fixes this issue

**Comment by michael-grunder** [comment]
You want `php --ri relay` to get info about the relay extension.  `php -ri` will attempt to execute `i` as PHP code.

```
❯ php -ri relay
PHP Parse error:  syntax error, unexpected end of file in Command line code on line 1
```
```bash
❯ php --ri relay

relay

Relay Support => enabled
Relay Version => 0.5.2-dev
Available serializers => php, json, igbinary, msgpack
Available compression => lzf, zstd, lz4
Git SHA => 65533f67384670a2dd393ec0cc1e3981b6000764
relay.enabled => true
relay.key =>
relay.maxmemory => 1073741824
relay.maxmemory_pct => 75
relay.maxmemory_limit => -1
relay.eviction_policy => noeviction
relay.eviction_sample_keys => 128
relay.initial_readers => 128
relay.invalidation_poll_usec => 5
relay.pconnect_default => 1
```

Note that I didn't inject a UUID, so you're probably getting the "default uuid warning":

```bash
fb462c08ef7c:/usr/local/lib/php/extensions/no-debug-non-zts-20220830# php
PHP Warning:  PHP Startup: Relay is using the default binary ID in Unknown on line 0

Warning: PHP Startup: Relay is using the default binary ID in Unknown on line 0
```

On the container you can fix that with this:

```bash
sed -i "s/00000000-0000-0000-0000-000000000000/$(cat /proc/sys/kernel/random/uuid)/" $(php-config --extension-dir)/relay.so
```

**Comment by k0d3r1s** [comment]
Oh, my bad. You're right, i'm missing one hyphen :(  
Now all is great, everything works :)

**Comment by simpletoimplement** [comment]
Awesome. When we should get an official build that is not a zip in comment? :)

**Comment by michael-grunder** [comment]
I should have them up today.

**Comment by simpletoimplement** [comment]
small reminder question on when we could get a build?

**Comment by tillkruss** [comment]
If you need the 8.3 build urgently, then don't install phpiredis and relay at the same time.

**Comment by michael-grunder** [comment]
You should be able to use the `relay-ck-pkg.so` file in the [Alpine 8.3 tarball](https://builds.r2.relay.so/dev/relay-dev-php8.3-alpine-x86-64.tar.gz).  That's basically what I uploaded to the thread earlier this week.

**Comment by k0d3r1s** [comment]
awesome, thank you :heart:

**Comment by k0d3r1s** [comment]
Warning: PHP Startup: Unable to load dynamic library 'relay.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220830/relay.so (Error loading shared library libhiredis.so.1.0.1-dev: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20220830/relay.so)

**Comment by michael-grunder** [comment]
Yeah, it didn't link with the right version of hiredis in the pipeline build.  I'll get another build and confirm it's correct then update the thread.

**Comment by michael-grunder** [comment]
Both `relay-pkg.so` and `relay-ck-pkg.so` from the alpine tarball should work.  It's probably better to use `relay-ck-pkg.so` which links with hiredis dynamically, since `phpiredis` is also linking with hiredis dynamically.

```bash
wget -q https://builds.r2.relay.so/dev/relay-dev-php8.3-alpine-x86-64.tar.gz && \
tar xvf relay-dev-php8.3-alpine-x86-64.tar.gz >/dev/null && \
cd relay-dev-php8.3-alpine-x86-64 && \
ldd relay-ck-pkg.so|grep hiredis
	libhiredis.so.1.1.0 => /usr/local/lib/libhiredis.so.1.1.0 (0x00007f8f5a40d000)
	libhiredis_ssl.so.1.1.0 => /usr/local/lib/libhiredis_ssl.so.1.1.0 (0x00007f8f5a406000)"
```

**Comment by k0d3r1s** [comment]
it works :)
