### ISSUE TITLE
Error when trying to apt install php8.2-relay 

### ISSUE THREAD

**Issue by nickchomey** [cachewerk/relay#57]
I have ondrej's php repo installed and installed `php(7.4-8.1)-relay`, along with any dependencies. But I get this error when trying to install `php8.2-relay`. I've tried for versions 0.5.1-0.6.2 (8.2 doesnt seem to exist before 0.5.1). It seems to be using the wrong date code thing.... `20210902` instead of `20220829`

```
Unpacking php8.2-relay (0.6.2) ...
dpkg: error processing archive /var/cache/apt/archives/php8.2-relay_0.6.2_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/php/20210902/relay.so', which is also in package php8.1-relay 0.6.2
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/php8.2-relay_0.6.2_amd64.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by tillkruss** [comment]
These were indeed wrong 😬 See https://github.com/cachewerk/linux-repos/commit/484bd1925c6abc27b9e712e8418c6e16e1bb952c

The repository will update in about 10 minutes 👍

**Comment by tillkruss** [comment]
Gotcha 🤦‍♂️ Fixed in https://github.com/cachewerk/linux-repos/commit/6695278ea131d6f130a1d02b514cf4f7bf64d0b5

**Comment by tillkruss** [comment]
Yeah, they were cached at the edge. I've flushed v0.6.2. Try again.

**Comment by tillkruss** [comment]
Glad to hear it!
