### ISSUE TITLE
Interrupted system call (RELAY_ERR_IO)

### ISSUE THREAD

**Issue by bjarn** [cachewerk/relay#74]
## Description
I am using Relay as a replacement for php-redis/predis in a Laravel 10 project. 

Now with Relay, I see `poll(2): Interrupted system call (RELAY_ERR_IO; cache.c:551)`.

![Screenshot 2023-05-30 at 14 18 32](https://github.com/cachewerk/relay/assets/14638441/546628db-a6d6-4208-95be-0828c8510a55)

![Screenshot 2023-05-30 at 14 18 40](https://github.com/cachewerk/relay/assets/14638441/2f49bc97-95e4-45d0-bf6c-a05b7d8c72ca)

This only happens on a server (queue worker) on a more remote location with more latency (around 100-200ms max.) to the Redis server, which is located in Germany and the worker in the USA (Miami).

## Expected Behavior
Queue should not throw exceptions.

## Actual Behavior
Throws the described exception at random times. Queue still works, but is logging this exception sometimes.

## Steps to Reproduce
Almost impossible, but:
1. Run a Redis server on location A and a worker that connects to it on Location B, other side of the world
2. Wait for a couple of hours, it should start throwing errors4.

## Additional context
Before, [I noticed different errors with php-redis that were common, but couldn't be solved.](https://github.com/phpredis/phpredis/issues/1881).

Apologies in advance for the lack of information. I'll update this issue as I discover more details.

## Relay diagnostics
```bash
$ php --ri relay

relay

Relay Support => enabled
Relay Version => 0.6.4
Available cache => 352
Available serializers => php, json, igbinary, msgpack
Available compression => lzf, zstd, lz4
Binary UUID => c773e2de-231e-484c-86d4-e51114e00975
Git SHA =>
Allocator => relay
License state => unknown
License memory cap => 0
License request id =>
relay.enabled => false
relay.key =>
relay.maxmemory => 0
relay.maxmemory_pct => 95
relay.eviction_policy => noeviction
relay.eviction_sample_keys => 128
relay.initial_readers => 128
relay.invalidation_poll_usec => 5
relay.pconnect_default => 1
relay.max_endpoint_dbs => 32
relay.loglevel => none
relay.logfile =>
```

## Environment
* Operating System and version: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-72-generic x86_64)
* PHP version: 8.2.6
* Laravel v10.11.0

**Comment by michael-grunder** [comment]
Thank you for the report, there's a lot of good info go to on here.

I will attempt to replicate and get back to you.

**Comment by michael-grunder** [comment]
I haven't been able to replicate the issue just yet, but I am pretty sure I've tracked down the only place this could be happening, which is actually in the underlying [hiredis connection logic](https://github.com/redis/hiredis/blob/af144563835849350015113e936e44bf2d44906a/net.c#L283), which is suspiciously similar to the PhpRedis error you were getting (`EINPROGRESS`).

This suggests that the same underlying condition is triggering the exception in both cases.

Do you happen to know whether signals are being delivered to these worker processes (e.g. sigint)?

**Comment by michael-grunder** [comment]
> Is there anything I can do to test/reproduce something more exactly now knowing this

I've got what I need for now but will let you know if I have any questions.

Honestly, it should be possible to mitigate this on Relay's side regardless of the specific underlying problem.

What hiredis does when it connects to a redis-server is switch the socket to non-blocking mode and then use `poll` to wait for success/failure.  At some point during this polling process, poll is returning `-1` and `errno` is set to `EINTR`.  This isn't a fatal error, it's just the kernel saying that the syscall was interrupted.

In other places in the hiredis code for example, we test for `EINTR` and then retry (e.g. `read` and `write` operations).

On Relay's side I can just detect that error in the underlying context and retry the connection myself.  The trick is that we don't want to do it in a way that would stop the process from being properly interrupted (e.g. if `SIGINT` were sent to shut down the queue process).

Once I trigger the condition it may even be worth fixing in hiredis, but I'm not sure about that yet.

**Comment by riasvdv** [comment]
We're also seeing this issue very regularly. Before we switched to Relay we had a lot of "Operation now in progress" exceptions with phpredis. We hoped using Relay would solve this but we're now getting this exception.

We're connecting to an external DigitalOcean managed Redis database, it is however in the same region as our servers, so I don't expect latency to be the big issue

**Comment by tillkruss** [comment]
@michael-grunder Did you figure out what this is?

**Comment by michael-grunder** [comment]
I've not been able to replicate the issue but will be able to fix/mitigate it.

**Comment by michael-grunder** [comment]
Quick update,

I have managed to replicate this error locally and am working on a fix.  There are some questions as to how exactly the fix should function.

The first solution that comes to my head is to use Relay's` Relay::OPT_MAX_RETRIES` setting to configure how many times Relay will retry the connection itself in the event of this specific `EINTR` issue.  Otherwise it could theoretically get into an infinite failure loop.

**Comment by michael-grunder** [comment]
I've implemented a fix for this by creating an option (`Relay::OPT_MAX_CONNECTION_RETRIES`) which is like `OPT_MAX_RETRIES` but applies to initial connections rather than retrying on an already established connection.

I've also added logic that will retry the connection if we get this specific `Interrupted system call` error from hiredis.  I'll reference this thread when we've got this into a release

**Comment by bjarn** [comment]
Great to hear! Keen to test it when it's released

**Comment by tillkruss** [comment]
We got this merged, but are fighting some macOS changes that are blocking a release. Tag should go out Monday.

**Comment by tillkruss** [comment]
v0.6.6 is out ✌️

**Comment by szepeviktor** [comment]
Could it be that images are still using v0.6.5?
https://github.com/search?q=repo%3Acachewerk%2Frelay%200.6.5&type=code

**Comment by szepeviktor** [comment]
A public release checklist will not hurt :)

**Comment by bjarn** [comment]
> v0.6.6 is out ✌️

@tillkruss Since the release, I haven't experienced this issue anymore. Thanks a lot!
![Screenshot 2023-07-24 at 23 26 17](https://github.com/cachewerk/relay/assets/14638441/f4525401-0105-4dde-bdd2-88a4b2af9c63)

**Comment by tillkruss** [comment]
Fantastic!

**Comment by michael-grunder** [comment]
This has also been fixed in upstream hiredis, so the Relay mitigation can be removed eventually.

[PR for reference](https://github.com/redis/hiredis/pull/1213)

**Comment by dzuelke** [comment]
@michael-grunder can you share your reproduce code?

**Comment by michael-grunder** [comment]
[Here's a git bundle with a reproducer](https://github.com/cachewerk/relay/files/12315908/eintr.bundle.gz)

Keep in mind I was reproducing the bug in Relay, not phpredis, so it may not be fully applicable.  The basic idea is that the `poll.php` script subscribes to a Redis channel waiting for `reproduce.php` to tell it that it is about to attempt a connection.

Then, using a configurable randomized delay range, `poll.php` will then signal the other process.  It's probably helpful to pass a remote host and port to `reproduce.php` so it's not connecting just to`localhost`, but you can play around with a variety of options.

**Comment by tillkruss** [comment]
@dzuelke: Happy to help out with anything you're cooking up.
