### ISSUE TITLE
Data is not accessible even though it exists 

### ISSUE THREAD

**Issue by roimee6** [cachewerk/relay#79]
Data is not accessible even though it exists 

## Description

I create a datum (a hash) -> I retrieve a single datum from the hash -> It returns null even though it exists

But if I do:

I create a datum (a hashe) -> I ask for the whole hashe (hgetall) -> I ask for a single datum of the hashe -> I can access the datum

It's strange
## Expected Behavior
Recover data instantly without having to retrieve the entire hash

## Actual Behavior
Data is null

## Steps to Reproduce

1. Create a hashe
2. Get an field of hash

## Relay diagnostics

```
Relay Support => enabled
Relay Version => 0.6.5
Available cache => 134163328
Available serializers => php, json, igbinary, msgpack
Available compression => lzf, zstd, lz4
Binary UUID => 9353abef-b2f0-4dce-bb13-fb15c332e964
Git SHA =>
Allocator => relay
License state => unknown
License memory cap => 0
License request id =>
relay.enabled => true
relay.key =>
relay.maxmemory => 134217728
relay.maxmemory_pct => 95
relay.eviction_policy => lru
relay.eviction_sample_keys => 128
relay.initial_readers => 128
relay.invalidation_poll_usec => 5
relay.pconnect_default => 1
relay.max_endpoint_dbs => 32
relay.loglevel => none
relay.logfile =>
...
```

## Environment

* Operating System and version: Debian
* PHP version: 8.1

**Comment by tillkruss** [comment]
Please post a code example of what you're doing and what you'd expect.

**Comment by michael-grunder** [comment]
@roimee6 Can you post a small bit of source code that replicates the bug?  Also are you using Relay in threads for this as well?
