### ISSUE TITLE
PHP Fatal error:  Uncaught Relay\Exception: Server closed the connection

### ISSUE THREAD

**Issue by riasvdv** [cachewerk/relay#85]
## Description

When we deploy our Laravel app to production with the Laravel integration, even before setting `REDIS_CLIENT=relay`, it produces a fatal error:

```
2023/07/05 08:19:07 [error] 3816576#3816576: *10974870 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Relay\Exception: Server closed the connection (RELAY_ERR_EOF; relay.c:1094) in releases/20230705-081029/vendor/cachewerk/relay/src/Laravel/RelayConnector.php:80
Stack trace:
#0 /releases/20230705-081029/vendor/cachewerk/relay/src/Laravel/RelayConnector.php(80): Relay\Relay->select()
#1 /releases/20230705-081029/vendor/cachewerk/relay/src/Laravel/RelayConnector.php(33): CacheWerk\Relay\Laravel\RelayConnector->createClient()
#2 /releases/20230705-081029/vendor/cachewerk/relay/src/Laravel/RelayConnector.php(38): CacheWerk\Relay\Laravel\RelayConnector->CacheWerk\Relay\Laravel\{closure}()
#3 /releases/20230705-081029/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(110): CacheWerk\Relay\Laravel\RelayConnector->connect()
#4 /releases/20230705-081029/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(91...; PHP message: PHP Fatal error:  Uncaught Relay\Exception: Server closed the connection (RELAY_ERR_EOF; relay.c:1094) in /releases/20230705-081029/vendor/cachewerk/relay/src/Laravel/RelayConnector.php:80
```

We are using DigitalOcean's managed Redis. The `REDIS_HOST` is currently set to something similar to this: `tlsv1.2://private-xxx-redis-1-do-user-xxx-0.b.db.ondigitalocean.com`

This error makes it hard for us to test what is configured wrong, as even installing the package causes the fatal error to happen.

## Expected Behavior

No fatal error when not setting `REDIS_CLIENT=relay` yet.

## Relay diagnostics

```
Relay Support => enabled
Relay Version => 0.6.5
Available cache => 160
Available serializers => php, json, igbinary, msgpack
Available compression => lzf, zstd, lz4
Binary UUID => 5bef8c1a-3b5f-4bba-ab37-23def9fed0eb
Git SHA => 6c2bffbe43d7da174f50647ac6790be55da64cb4
Allocator => relay
License state => unknown
License memory cap => 0
License request id =>  
relay.enabled => false
relay.key =>  
relay.maxmemory => 0
relay.maxmemory_pct => 95
relay.eviction_policy => noeviction
relay.eviction_sample_keys => 128
relay.initial_readers => 128
relay.invalidation_poll_usec => 5
relay.pconnect_default => 1
relay.max_endpoint_dbs => 32
relay.loglevel => none
relay.logfile =>  

```

## Environment

* Operating System and version: Ubuntu 20.04.1 LTS
* PHP version: 8.2.3

**Comment by michael-grunder** [comment]
Thanks for the report.

It would appear that the app is still trying to instance a Relay connection even if you don't configure Relay as the Redis client.

@tillkruss I'm not really sure about the mechanics here, but let me know if you have any insight.

As for Relay itself, are you able to connect to your Redis instance with a little test script?

Something like this:

```php
use \Relay\Relay;
$relay = new Relay(YOUR_REDIS_HOST, YOUR_REDIS_PORT);
var_dump($relay->ping());
var_dump($relay->select(1));
```

The fact that you're getting an `EOF` exception is a hint that this may be TLS related.  I will test Relay against that kind of URI.

**Comment by riasvdv** [comment]
We have been able to solve the connecting, it was a combination of some config settings we had. Right now our error tracker is reporting #74 regularly which we're trying to find the cause of.

**Comment by tillkruss** [comment]
@riasvdv Would you mind sharing what settings you changed to resolve this?

**Comment by riasvdv** [comment]
@tillkruss we had to remove the tlsv1.2:// prefix, and add the following to our Redis connections in `config/database.php`:

```
'scheme' => env('REDIS_SCHEME', 'tcp'),
```

Then set a `REDIS_SCHEME=tls` environment variable for production.

It would have been a lot easier to debug if we didn't have a fatal error just by installing the package

**Comment by tillkruss** [comment]
Thanks. What was the fatal error?
