### ISSUE TITLE
Segfault error 4 in relay.so

### ISSUE THREAD

**Issue by bjarn** [cachewerk/relay#94]
## Description
We noticed segmentation faults in the syslog after our process relying on Relay suddenly stopped responding, however it kept running because of this.

## Expected Behavior
Segfault should not happen

## Actual Behavior
At random moments, the process stops but thinks it's still running. Syslog contains the following entries and stops logging related entries afterwards:
```
Jul 17 11:22:05 worker-ams-1 kernel: [9976222.404683] php8.2[1344270]: segfault at 64b52475 ip 00007f646f71feb0 sp 00007ffff0b01bf0 error 4 in relay.so[7f646f6e3000+7b000]
Jul 17 11:22:05 worker-ams-1 kernel: [9976222.404746] Code: 9c 66 0f 1f 84 00 00 00 00 00 49 8b 54 24 08 48 8d 7c 24 50 48 89 ee e8 0e ef ff ff e9 b1 fe ff ff 66 0f 1f 84 00 00 00 00 00 <48> 8b 56 18 48 8b 76 20 48 8d bd d8 02 00 00 4c 8d 6c 24 20 e8 f7
Jul 17 11:22:05 worker-ams-1 kernel: [9976222.415398] php8.2[1344332]: segfault at 64b52475 ip 00007fe30faabeb0 sp 00007ffdcaf9c8f0 error 4 in relay.so[7fe30fa6f000+7b000]
Jul 17 11:22:05 worker-ams-1 kernel: [9976222.415428] Code: 9c 66 0f 1f 84 00 00 00 00 00 49 8b 54 24 08 48 8d 7c 24 50 48 89 ee e8 0e ef ff ff e9 b1 fe ff ff 66 0f 1f 84 00 00 00 00 00 <48> 8b 56 18 48 8b 76 20 48 8d bd d8 02 00 00 4c 8d 6c 24 20 e8 f7
Jul 17 11:22:11 worker-ams-1 kernel: [9976228.540757] php8.2[1344272]: segfault at 64b5247b ip 00007f961790ceb0 sp 00007ffd5bbe3f50 error 4 in relay.so[7f96178d0000+7b000]
Jul 17 11:22:11 worker-ams-1 kernel: [9976228.540793] Code: 9c 66 0f 1f 84 00 00 00 00 00 49 8b 54 24 08 48 8d 7c 24 50 48 89 ee e8 0e ef ff ff e9 b1 fe ff ff 66 0f 1f 84 00 00 00 00 00 <48> 8b 56 18 48 8b 76 20 48 8d bd d8 02 00 00 4c 8d 6c 24 20 e8 f7
Jul 17 11:22:11 worker-ams-1 kernel: [9976228.548304] php8.2[1344331]: segfault at 64b5247b ip 00007f935fb51eb0 sp 00007ffd07b32b50 error 4 in relay.so[7f935fb15000+7b000]
Jul 17 11:22:11 worker-ams-1 kernel: [9976228.548323] Code: 9c 66 0f 1f 84 00 00 00 00 00 49 8b 54 24 08 48 8d 7c 24 50 48 89 ee e8 0e ef ff ff e9 b1 fe ff ff 66 0f 1f 84 00 00 00 00 00 <48> 8b 56 18 48 8b 76 20 48 8d bd d8 02 00 00 4c 8d 6c 24 20 e8 f7
```

## Steps to Reproduce
In my case:
1. Run Laravel Horizon process
2. Let it access a remote redis server
3. ...wait

## Additional context
As mentioned, it's hard to have a easy way to reproduce. However, segfault means it's trying to access memory of another process or OS. Possibly a security violation.

This error did not happen when using phpredis though.

## Relay diagnostics
```
xxx@worker-ams-1:~$ php --ri relay

relay

Relay Support => enabled
Relay Version => 0.6.5
Available cache => 160
Available serializers => php, json, igbinary, msgpack
Available compression => lzf, zstd, lz4
Binary UUID => a357017c-a66b-4420-96bd-5c9c08320800
Git SHA =>
Allocator => relay
License state => unknown
License memory cap => 0
License request id =>
relay.enabled => false
relay.key =>
relay.maxmemory => 0
relay.maxmemory_pct => 95
relay.eviction_policy => noeviction
relay.eviction_sample_keys => 128
relay.initial_readers => 128
relay.invalidation_poll_usec => 5
relay.pconnect_default => 1
relay.max_endpoint_dbs => 32
relay.loglevel => none
relay.logfile =>
```

## Environment

* Operating System and version: 
```
Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-76-generic x86_64)
```
* PHP version:
```
PHP 8.2.8 (cli) (built: Jul  8 2023 07:10:21) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.8, Copyright (c), by Zend Technologies
```

**Comment by michael-grunder** [comment]
Hi, thanks for the report.

I'll work with Till to try and replicate the crash in Laravel.  Failing that however, it would be helpful if you were able to generate a stack trace.  If you're running fpm you can configure it to drop core dumps when a worker process crashes.  With a core dump and the PHP binary you are using I may be able to narrow down where things are failing.

Are you using SSL connections?  We have a known issue where Relay (which uses hiredis) is linking to openssl v1.1 but PHP is linking to openssl v3.  Vice versa can also cause the issue.

You could check this by doing something like:

```bash
ldd $(which php)
ldd $(php-config --extention-dir)/relay.so
ldd /usr/local/lib/libhiredis_ssl.so
```

If you see the binaries linking to both openssl v1.1 and openssl v3 that is likely the issue (assuming you are using SSL)

**Comment by bjarn** [comment]
It sadly hasn't happened since yesterday, so no stacktraces. I know it's making it very difficult - it was the first thing I looked at until someone gave me the hint to look at the syslog.
It also isn't a php-fpm process, just a supervisor keeping a php cli process alive. Sadly I might've been too late, the coredump folder is already emptied.

@michael-grunder not using SSL here, still providing some output just in case:
```
# ldd /usr/local/lib/libhiredis_ssl.so
ldd: /usr/local/lib/libhiredis_ssl.so: No such file or directory
```

```
# ldd $(which php)
	linux-vdso.so.1 (0x00007fff96b86000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb08779e000)
	libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fb0875bc000)
	libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007fb087518000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007fb0870d6000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fb08703a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb08701e000)
	libsodium.so.23 => /lib/x86_64-linux-gnu/libsodium.so.23 (0x00007fb086fc4000)
	libargon2.so.1 => /lib/x86_64-linux-gnu/libargon2.so.1 (0x00007fb086fba000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb086d92000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb087e1a000)
	libicuuc.so.70 => /lib/x86_64-linux-gnu/libicuuc.so.70 (0x00007fb086b97000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fb086b6c000)
	libicudata.so.70 => /lib/x86_64-linux-gnu/libicudata.so.70 (0x00007fb084f4c000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb084d22000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb084d02000)
```

If I get any more information, I'll share it!

**Comment by michael-grunder** [comment]
Could I see what `relay.so` is linking against?

```bash
ldd $(php-config --extension-dir)/relay.so
```

If you don't have `php-config` you just need to find where the PHP extensions are installed and use the full path.

**Comment by bjarn** [comment]
@michael-grunder Of course, got it!

```
# ldd $(php-config --extension-dir)/relay.so
	linux-vdso.so.1 (0x00007ffff61cc000)
	libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f069c531000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f069c0ef000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f069c020000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f069c000000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f069bdd8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f069c6ac000)
```

**Comment by michael-grunder** [comment]
Unfortunately this looks fine.  The only real way to narrow it down is some kind of a stack trace as there are no known (non SSL related) crashes.

I'll see about adding a backtrace to Relay itself, which could be logged via our logging mechanism.

**Comment by bjarn** [comment]
Hi - I know it doesn't help, but I just had this issue again, however, I couldn't find a coredump again and no segfaults on the timestamp the process stopped working, but I did see some lines over the last few days.

Is there anything you could recommend to me to try to get more information on this issue? Would love to help out, but it's really above my knowledge level atm.

**Comment by michael-grunder** [comment]
Are you guys still running v0.6.5?  We recently released v0.6.6 and there are a couple of fixes in there that could have potentially led to a segfault.

Can you give me a little info on what the laravel horizon process does with redis?  Are these long running queue processes?

**Comment by michael-grunder** [comment]
I took a guess that you are using the Ubuntu 22.04+ssl3 shared object and was able to find this code in the binary.  

The crash is occurring in `Relay::exec()`.  There was actually a bugfix in v0.6.6 that involved transactions although I won't just assume this is the same issue.  Still, given that this narrows down the issue a great deal it should improve our ability to find it.

**Comment by bjarn** [comment]
> I took a guess that you are using the Ubuntu 22.04+ssl3 shared object and was able to find this code in the binary.
> 
> The crash is occurring in `Relay::exec()`. There was actually a bugfix in v0.6.6 that involved transactions although I won't just assume this is the same issue. Still, given that this narrows down the issue a great deal it should improve our ability to find it.

Ah that sounds great! I updated yesterday, now running v0.6.6.

php8.2-relay/jammy,now 0.6.6 amd64 [installed]

I will keep a close eye on it and see if it happens again.

> Can you give me a little info on what the laravel horizon process does with redis? Are these long running queue processes?

Yep, that's basically what it does. It's managing long-running processes and spawns more when it gets busy. Eventually it executes the job on the background.

**Comment by tillkruss** [comment]
@bjarn: LMK if the error is gone, if not I'll set up Horizon locally and try to reproduce this.

**Comment by tillkruss** [comment]
@bjarn: Alright, keep me posted.

**Comment by tillkruss** [comment]
@bjarn: Can you post your `config/horizon.php` file?
